import { Ionicons, MaterialCommunityIcons } from "@expo/vector-icons";
import { useEffect, useMemo, useState } from "react";
import { router, useLocalSearchParams, useNavigation } from "expo-router";
import { ActivityIndicator, Alert, RefreshControl, ScrollView, StyleSheet, Text, TouchableOpacity, View } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import { useDetail } from "../hooks/useCrud";
import { apiGet, apiPost } from "../lib/api";
import { smartBack } from "../lib/navigationHistory";

type TabKey = "stats" | "details" | "units" | "contracts";
type Unit = { id: number; unit_number?: string | null; floor?: string | number | null; status?: string | null; rent_amount?: number | string | null; contracts_count?: number; contracts?: Array<{ id: number }> };
type PropertyDetail = { id: number; name?: string | null; city?: string | null; district?: string | null; address?: string | null; deed_number?: string | null; document_number?: string | null; document_date_hijri?: string | null; document_date_gregorian?: string | null; property_type?: string | null; usage_type?: string | null; management_type?: string | null; floors_count?: number | string | null; elevators_count?: number | string | null; parking_spots_count?: number | string | null; notes?: string | null; total_rent_amount?: number | string | null; property_contracts_count?: number; unit_contracts_count?: number; can_create_contract?: boolean; owner?: { id: number; name?: string | null } | null; units?: Unit[]; expenses?: Array<{ id: number; amount?: number | string | null; title?: string | null }> };
type Payment = { amount?: number | string | null; remaining_amount?: number | string | null; paid_amount?: number | string | null; due_date?: string | null; status?: string | null };
type Contract = { id: number; contract_number?: string | null; government_contract_number?: string | null; rent_amount?: number | string | null; status?: string | null; start_date?: string | null; end_date?: string | null; unit_id?: number | string | null; payments?: Payment[]; tenant?: { name?: string | null; phone?: string | null; mobile?: string | null } | null; unit?: { id?: number | string | null; unit_number?: string | null } | null };

type OverdueInfo = { count: number; amount: number };

const tabs: Array<{ key: TabKey; label: string; icon: keyof typeof Ionicons.glyphMap }> = [
  { key: "stats", label: "إحصائيات", icon: "stats-chart-outline" },
  { key: "details", label: "تفاصيل", icon: "list-outline" },
  { key: "units", label: "الوحدات", icon: "home-outline" },
  { key: "contracts", label: "العقود", icon: "document-text-outline" },
];

const typeMap: Record<string, string> = { building: "عمارة", apartment: "شقة", villa: "فيلا", land: "أرض", commercial: "تجاري", mixed: "مختلط", other: "أخرى" };
const titleMap: Record<string, string> = { building: "تفاصيل العمارة", apartment: "تفاصيل الشقة", villa: "تفاصيل الفيلا", land: "تفاصيل الأرض", commercial: "تفاصيل العقار التجاري", mixed: "تفاصيل العقار المختلط", other: "تفاصيل العقار" };
const usageMap: Record<string, string> = { residential: "سكني", commercial: "تجاري", mixed: "مختلط" };
const managementMap: Record<string, string> = { owned: "ملك خاص", managed: "إدارة للغير" };
const unitStatusMap: Record<string, string> = { rented: "مؤجرة", available: "شاغرة", maintenance: "صيانة" };

function hasValue(v: unknown) { return v !== null && v !== undefined && String(v).trim() !== "" && String(v).trim() !== "-"; }
function display(v: unknown) { return hasValue(v) ? String(v) : "-"; }
function num(v: unknown) { const n = Number(String(v ?? 0).replace(/,/g, "")); return Number.isFinite(n) ? n : 0; }
function money(v: unknown) { return `${Math.round(num(v)).toLocaleString("ar-SA")} ر.س`; }
function encoded(v: unknown) { return encodeURIComponent(String(v ?? "")); }
function contractsList(payload: any): Contract[] { return Array.isArray(payload?.data) ? payload.data : Array.isArray(payload) ? payload : []; }
function status(v?: string | null) { return String(v || "").trim().toLowerCase(); }
function isActiveContract(c: Contract) { return ["active", "نشط", "open", "current", "ساري", "مفتوح"].includes(status(c.status)); }
function ymd(v?: string | null) { const m = String(v || "").match(/^(\d{4}-\d{2}-\d{2})/); return m ? m[1] : ""; }
function today() { const d = new Date(); return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, "0")}-${String(d.getDate()).padStart(2, "0")}`; }
function remaining(p: Payment) { return hasValue(p.remaining_amount) ? num(p.remaining_amount) : Math.max(0, num(p.amount) - num(p.paid_amount)); }
function isOverduePayment(p: Payment, t: string) { const s = status(p.status); if (["paid", "مدفوع", "cancelled", "canceled", "ملغي"].includes(s)) return false; if (["overdue", "متأخر", "متأخرة"].includes(s)) return true; const d = ymd(p.due_date); return /^\d{4}-\d{2}-\d{2}$/.test(d) && d < t; }
function unitContractsCount(unit: Unit) { return typeof unit.contracts_count === "number" ? unit.contracts_count : Array.isArray(unit.contracts) ? unit.contracts.length : 0; }
function unitSortLabel(unit: Unit) { return String(unit.unit_number || `وحدة #${unit.id}`).trim(); }
function contractUnitId(c: Contract) { return String(c.unit_id ?? c.unit?.id ?? ""); }
function tenantPhone(contract?: Contract) { return contract?.tenant?.phone || contract?.tenant?.mobile || ""; }
function contractNo(c: Contract) { return c.contract_number || c.government_contract_number || `عقد #${c.id}`; }
function unitText(c: Contract) { return c.unit?.unit_number ? `الوحدة: ${c.unit.unit_number}` : contractUnitId(c) ? `وحدة #${contractUnitId(c)}` : "عقد على العقار"; }

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return <View style={styles.sectionCard}><Text style={styles.sectionTitle}>{title}</Text>{children}</View>;
}
function Row({ label, value }: { label: string; value: unknown }) {
  if (!hasValue(value)) return null;
  return <View style={styles.infoRow}><Text style={styles.infoValue}>{display(value)}</Text><Text style={styles.infoLabel}>{label}</Text></View>;
}
function StatTile({ icon, value, label, danger = false }: { icon: keyof typeof MaterialCommunityIcons.glyphMap; value: unknown; label: string; danger?: boolean }) {
  return <View style={[styles.statTile, danger ? styles.statTileDanger : null]}><View style={[styles.statIconBox, danger ? styles.statIconDanger : null]}><MaterialCommunityIcons name={icon} size={22} color={danger ? "#DC2626" : "#0F766E"} /></View><Text style={[styles.statValue, danger ? styles.statValueDanger : null]} numberOfLines={1}>{display(value)}</Text><Text style={[styles.statLabel, danger ? styles.statLabelDanger : null]}>{label}</Text></View>;
}
function ContractCard({ contract }: { contract: Contract }) {
  const tenantName = contract.tenant?.name || "مستأجر غير محدد";
  const phone = tenantPhone(contract);
  return <TouchableOpacity style={styles.contractCard} activeOpacity={0.9} onPress={() => router.push(`/contract/${contract.id}` as never)}><View style={styles.contractIcon}><MaterialCommunityIcons name="file-document-check-outline" size={22} color="#0F766E" /></View><View style={styles.contractInfo}><Text numberOfLines={1} style={styles.contractTitle}>{contractNo(contract)}</Text><Text numberOfLines={1} style={styles.contractMeta}>{tenantName}</Text><Text numberOfLines={1} style={styles.contractMeta}>{unitText(contract)}</Text>{phone ? <Text numberOfLines={1} style={styles.contractPhone}>الجوال: {phone}</Text> : null}</View><View style={styles.contractSide}><Text style={styles.contractStatus}>{contract.status || "-"}</Text><Text style={styles.contractAmount}>{money(contract.rent_amount)}</Text><Ionicons name="chevron-back" size={16} color="#64748B" /></View></TouchableOpacity>;
}
function UnitCard({ unit, overdueInfo, activeContract }: { unit: Unit; overdueInfo?: OverdueInfo; activeContract?: Contract }) {
  const hasContract = unitContractsCount(unit) > 0;
  const hasOverdue = !!overdueInfo && overdueInfo.count > 0;
  const tenantName = activeContract?.tenant?.name || "";
  const phone = tenantPhone(activeContract);
  return <TouchableOpacity style={[styles.unitCard, hasOverdue ? styles.unitCardDanger : null]} activeOpacity={0.9} onPress={() => router.push(`/unit/${unit.id}` as never)}><View style={[styles.unitIconBox, hasOverdue ? styles.unitIconBoxDanger : null]}><MaterialCommunityIcons name="door" size={22} color={hasOverdue ? "#DC2626" : "#0F766E"} /></View><View style={styles.unitInfoBox}><Text style={[styles.unitTitle, hasOverdue ? styles.unitTitleDanger : null]}>{unit.unit_number || `وحدة #${unit.id}`}</Text><Text style={styles.unitMeta}>الدور {display(unit.floor)}</Text>{activeContract && tenantName ? <Text style={styles.unitTenantText}>المستأجر: {tenantName}</Text> : null}{activeContract && phone ? <Text style={styles.unitPhoneText}>الجوال: {phone}</Text> : null}{hasOverdue ? <Text style={styles.unitOverdueText}>متأخرات {overdueInfo.count.toLocaleString("ar-SA")} / {money(overdueInfo.amount)}</Text> : <Text style={hasContract ? styles.unitContractOk : styles.unitContractEmpty}>{hasContract ? `يوجد ${unitContractsCount(unit)} عقد` : "لا يوجد عقد"}</Text>}</View><View style={styles.unitSideBox}><Text style={[styles.unitStatus, hasOverdue ? styles.unitStatusDanger : null]}>{unitStatusMap[String(unit.status || "")] || unit.status || "-"}</Text><Text style={[styles.unitRent, hasOverdue ? styles.unitRentDanger : null]}>{money(unit.rent_amount)}</Text><Ionicons name="chevron-back" size={16} color={hasOverdue ? "#DC2626" : "#64748B"} /></View></TouchableOpacity>;
}

export default function PropertyDetailScreen() {
  const { id } = useLocalSearchParams<{ id: string }>();
  const navigation = useNavigation();
  const { data, loading, error, reload } = useDetail<PropertyDetail>({ endpoint: `/properties/${id}` });
  const [menuOpen, setMenuOpen] = useState(false);
  const [activeTab, setActiveTab] = useState<TabKey>("stats");
  const [propertyContracts, setPropertyContracts] = useState<Contract[]>([]);
  const [contractsReloadKey, setContractsReloadKey] = useState(0);

  const shouldReturnAfterDelete = !!error && /No query results|not found|غير موجود/i.test(String(error));
  const isApartmentProperty = String(data?.property_type || "") === "apartment";
  const units = data?.units || [];
  const sortedUnits = useMemo(() => [...units].sort((a, b) => unitSortLabel(a).localeCompare(unitSortLabel(b), "ar", { numeric: true, sensitivity: "base" })), [units]);
  const rented = units.filter((unit) => unit.status === "rented").length;
  const available = units.filter((unit) => unit.status === "available").length;
  const totalRent = data && hasValue(data.total_rent_amount) ? num(data.total_rent_amount) : units.reduce((sum, unit) => sum + num(unit.rent_amount), 0);
  const totalExpenses = (data?.expenses || []).reduce((sum, expense) => sum + num(expense.amount), 0);
  const propertyId = data?.id || Number(id || 0);
  const encodedPropertyName = encoded(data?.name || `عقار #${propertyId}`);
  const ownerQuery = data?.owner?.id ? `&owner_id=${data.owner.id}&owner_name=${encoded(data.owner.name || "")}` : "";
  const unitContracts = units.reduce((sum, unit) => sum + unitContractsCount(unit), 0);
  const totalContracts = Number(data?.property_contracts_count || 0) + Number(data?.unit_contracts_count ?? unitContracts);
  const propertyTypeLabel = typeMap[String(data?.property_type || "")] || data?.property_type || "عقار";
  const activeContracts = useMemo(() => propertyContracts.filter(isActiveContract), [propertyContracts]);
  const displayContracts = propertyContracts.length ? propertyContracts : activeContracts;
  const activeContractsCount = propertyContracts.length > 0 ? activeContracts.length : totalContracts;
  const canCreateContract = data ? (typeof data.can_create_contract === "boolean" ? data.can_create_contract : totalContracts === 0) : false;

  const activeContractByUnit = useMemo(() => { const map: Record<string, Contract> = {}; activeContracts.forEach((contract) => { const key = contractUnitId(contract); if (key && !map[key]) map[key] = contract; }); return map; }, [activeContracts]);
  const overdueStats = useMemo(() => { const t = today(); const payments = activeContracts.flatMap((contract) => contract.payments || []).filter((payment) => isOverduePayment(payment, t)); return { count: payments.length, amount: payments.reduce((sum, payment) => sum + remaining(payment), 0) }; }, [activeContracts]);
  const overdueByUnit = useMemo(() => { const t = today(); const map: Record<string, OverdueInfo> = {}; activeContracts.forEach((contract) => { const key = contractUnitId(contract); if (!key) return; const payments = (contract.payments || []).filter((payment) => isOverduePayment(payment, t)); if (!payments.length) return; if (!map[key]) map[key] = { count: 0, amount: 0 }; map[key].count += payments.length; map[key].amount += payments.reduce((sum, payment) => sum + remaining(payment), 0); }); return map; }, [activeContracts]);
  const detailsRows = useMemo(() => { if (!data) return [] as Array<[string, unknown]>; return [["النوع", propertyTypeLabel], ["الاستخدام", usageMap[String(data.usage_type || "")] || data.usage_type], ["الإدارة", managementMap[String(data.management_type || "")] || data.management_type], ["رقم الصك", data.deed_number || data.document_number], ["العنوان", data.address], ["عدد الأدوار", data.floors_count], ["المواقف", data.parking_spots_count], ["المصاعد", data.elevators_count], ["ملاحظات", data.notes]] as Array<[string, unknown]>; }, [data, propertyTypeLabel]);

  useEffect(() => { if (!shouldReturnAfterDelete) return; const timer = setTimeout(() => smartBack(), 250); return () => clearTimeout(timer); }, [shouldReturnAfterDelete]);
  useEffect(() => { if (!data) return; navigation.setOptions({ title: titleMap[String(data.property_type || "")] || "تفاصيل العقار" }); }, [data?.property_type, navigation]);
  useEffect(() => { if (!id) return; let cancelled = false; apiGet(`/contracts?property_id=${encoded(String(id))}`).then((result) => { if (!cancelled) setPropertyContracts(contractsList(result)); }).catch(() => { if (!cancelled) setPropertyContracts([]); }); return () => { cancelled = true; }; }, [id, data?.id, contractsReloadKey]);
  useEffect(() => { if (isApartmentProperty && activeTab === "units") setActiveTab("contracts"); }, [isApartmentProperty, activeTab]);

  function refresh() { reload(); setContractsReloadKey((v) => v + 1); }
  function closeMenu() { setMenuOpen(false); }
  function openEditProperty() { closeMenu(); router.push(`/property-form?id=${propertyId}` as never); }
  function openRepository() { closeMenu(); router.push(`/files?property_id=${propertyId}&property_name=${encodedPropertyName}${ownerQuery}` as never); }
  function openAddUnit() { closeMenu(); const q = new URLSearchParams(); if (data?.owner?.id) q.set("owner_id", String(data.owner.id)); q.set("property_type", "apartment"); q.set("lock_property_type", "1"); q.set("source_property_id", String(propertyId)); q.set("source_property_name", data?.name || `عقار #${propertyId}`); router.push(`/property-form?${q.toString()}` as never); }
  function openPropertyService(path: string) { closeMenu(); router.push(`${path}?property_id=${propertyId}&property_name=${encodedPropertyName}${ownerQuery}` as never); }
  function openCreateContract() { closeMenu(); Alert.alert("إضافة عقد", "اختر طريقة إضافة العقد:", [{ text: "رفع عقد PDF", onPress: () => router.push(`/upload-contract?property_id=${propertyId}&property_name=${encodedPropertyName}&contract_scope=property&target_type=property${ownerQuery}` as never) }, { text: "إنشاء عقد يدوي", onPress: () => router.push(`/create-contract?property_id=${propertyId}&property_name=${encodedPropertyName}&contract_scope=property&target_type=property${ownerQuery}` as never) }, { text: "إلغاء", style: "cancel" }]); }
  function confirmDeleteProperty() { closeMenu(); Alert.alert("حذف العقار", `هل تريد حذف ${data?.name || `عقار #${propertyId}`}؟`, [{ text: "إلغاء", style: "cancel" }, { text: "حذف", style: "destructive", onPress: async () => { try { await apiPost(`/edit-delete-center/properties/${propertyId}/delete`, {}); Alert.alert("تم", "تم حذف العقار.", [{ text: "حسنًا", onPress: () => smartBack() }]); } catch (e) { Alert.alert("تعذر الحذف", e instanceof Error ? e.message : "حدث خطأ غير متوقع"); } } }]); }

  if (loading || shouldReturnAfterDelete) return <SafeAreaView style={styles.safe}><View style={styles.loadingBox}><ActivityIndicator /><Text style={styles.loadingText}>جاري تحميل العقار...</Text></View></SafeAreaView>;
  if (error || !data) return <SafeAreaView style={styles.safe}><View style={styles.errorBox}><Text style={styles.errorTitle}>تعذر عرض العقار</Text><Text style={styles.errorText}>{String(error || "غير موجود")}</Text><TouchableOpacity style={styles.retryButton} onPress={refresh}><Text style={styles.retryText}>إعادة المحاولة</Text></TouchableOpacity></View></SafeAreaView>;

  return <SafeAreaView style={styles.safe} edges={["top"]}><ScrollView contentContainerStyle={styles.content} showsVerticalScrollIndicator={false} refreshControl={<RefreshControl refreshing={false} onRefresh={refresh} tintColor="#0F766E" />}>
    <View style={styles.heroCard}><View style={styles.heroTop}><View style={styles.heroIcon}><Text style={styles.heroEmoji}>{data.property_type === "villa" ? "🏡" : data.property_type === "apartment" ? "🏠" : data.property_type === "land" ? "🧭" : "🏢"}</Text></View><View style={styles.heroTextBox}><Text style={styles.heroType}>{propertyTypeLabel}</Text><Text style={styles.heroTitle}>{data.name || `عقار #${propertyId}`}</Text><View style={styles.heroLocationLine}><Ionicons name="location-outline" size={13} color="#CBD5E1" /><Text style={styles.heroSubtitle}>{[data.district, data.city].filter(Boolean).join("، ") || "لا يوجد موقع مسجل"}</Text></View>{data.owner?.name ? <Text style={styles.ownerText}>المالك: {data.owner.name}</Text> : null}</View></View></View>
    <View style={styles.tabsWrap}>{tabs.filter((tab) => !(isApartmentProperty && tab.key === "units")).map((tab) => { const active = activeTab === tab.key; return <TouchableOpacity key={tab.key} style={[styles.tabButton, active ? styles.tabButtonActive : null]} activeOpacity={0.88} onPress={() => setActiveTab(tab.key)}><Ionicons name={tab.icon} size={17} color={active ? "#0F172A" : "#64748B"} /><Text style={[styles.tabText, active ? styles.tabTextActive : null]}>{tab.label}</Text></TouchableOpacity>; })}</View>
    {activeTab === "stats" ? <View style={styles.sectionCard}><View style={styles.sectionHeader}><Text style={styles.sectionTitle}>الملخص</Text><Text style={styles.sectionSubtitle}>ملخص سريع عن هذا العقار فقط</Text></View><View style={styles.statsGrid}><StatTile icon="alert-circle-outline" value={money(overdueStats.amount)} label={`دفعات متأخرة (${overdueStats.count.toLocaleString("ar-SA")})`} danger={overdueStats.count > 0} /><StatTile icon="file-document-check-outline" value={activeContractsCount.toLocaleString("ar-SA")} label="العقود النشطة" /><StatTile icon="cash-multiple" value={money(totalRent)} label="إجمالي الإيجارات" /><StatTile icon="cash-minus" value={money(totalExpenses)} label="المصروفات" danger={totalExpenses > 0} /><StatTile icon="office-building" value={units.length.toLocaleString("ar-SA")} label="عدد الوحدات" /><StatTile icon="key-variant" value={rented.toLocaleString("ar-SA")} label="مؤجرة" /><StatTile icon="door-open" value={available.toLocaleString("ar-SA")} label="شاغرة" /></View></View> : null}
    {activeTab === "details" ? <><Section title="تفاصيل العقار">{detailsRows.map(([label, value]) => <Row key={label} label={label} value={value} />)}</Section></> : null}
    {activeTab === "units" ? <View style={styles.sectionCard}><View style={styles.sectionHeaderRow}><TouchableOpacity style={styles.smallAddButton} activeOpacity={0.88} onPress={openAddUnit}><Ionicons name="add" size={22} color="#fff" /></TouchableOpacity><View style={styles.sectionHeaderText}><Text style={styles.sectionTitle}>الوحدات</Text><Text style={styles.sectionSubtitle}>{units.length.toLocaleString("ar-SA")} وحدة مرتبطة بهذا العقار</Text></View></View>{sortedUnits.length > 0 ? sortedUnits.map((unit) => <UnitCard key={unit.id} unit={unit} overdueInfo={overdueByUnit[String(unit.id)]} activeContract={activeContractByUnit[String(unit.id)]} />) : <Text style={styles.emptyText}>لا توجد وحدات مضافة لهذا العقار.</Text>}</View> : null}
    {activeTab === "contracts" ? <View style={styles.sectionCard}><View style={styles.sectionHeaderRow}><TouchableOpacity style={styles.smallAddButton} activeOpacity={0.88} onPress={openCreateContract}><Ionicons name="add" size={22} color="#fff" /></TouchableOpacity><View style={styles.sectionHeaderText}><Text style={styles.sectionTitle}>العقود</Text><Text style={styles.sectionSubtitle}>{displayContracts.length.toLocaleString("ar-SA")} عقد مرتبط بهذا العقار</Text></View></View>{displayContracts.length ? displayContracts.map((contract) => <ContractCard key={contract.id} contract={contract} />) : <View style={styles.contractEmptyBox}><Text style={styles.emptyText}>{isApartmentProperty ? "هذه الشقة مستقلة، وعقودها تظهر هنا مباشرة." : "لا توجد عقود مرتبطة بهذا العقار."}</Text><TouchableOpacity style={styles.contractAddButton} onPress={openCreateContract}><Ionicons name="add" size={18} color="#fff" /><Text style={styles.contractAddText}>إنشاء / رفع عقد</Text></TouchableOpacity></View>}</View> : null}
    <View style={{ height: 78 }} />
  </ScrollView>{menuOpen ? <TouchableOpacity style={styles.floatingBackdrop} activeOpacity={1} onPress={closeMenu} /> : null}{menuOpen ? <View style={styles.floatingMenu}><MenuAction icon="pencil-outline" label="تعديل" color="#0F766E" onPress={openEditProperty} /><MenuAction icon="trash-can-outline" label="حذف" color="#DC2626" onPress={confirmDeleteProperty} />{!isApartmentProperty ? <MenuAction icon="plus-circle-outline" label="إضافة وحدة" color="#0F766E" onPress={openAddUnit} /> : null}<MenuAction icon="file-document-check-outline" label="العقود" color="#0F766E" onPress={() => { closeMenu(); setActiveTab("contracts"); }} /><MenuAction icon="cash-minus" label="المصروفات" color="#0F766E" onPress={() => openPropertyService("/expenses")} />{canCreateContract ? <MenuAction icon="file-sign" label="إنشاء / رفع عقد" color="#0F766E" onPress={openCreateContract} /> : null}<MenuAction icon="image-multiple-outline" label="الملفات والوسائط" color="#0F766E" onPress={openRepository} /></View> : null}<TouchableOpacity style={styles.floatingButton} activeOpacity={0.88} onPress={() => setMenuOpen((v) => !v)}><Ionicons name={menuOpen ? "close" : "ellipsis-vertical"} size={24} color="#fff" /></TouchableOpacity></SafeAreaView>;
}

function MenuAction({ icon, label, color = "#0F172A", onPress }: { icon: keyof typeof MaterialCommunityIcons.glyphMap; label: string; color?: string; onPress: () => void }) {
  return <TouchableOpacity style={styles.floatingMenuAction} activeOpacity={0.86} onPress={onPress}><MaterialCommunityIcons name={icon} size={21} color={color} /><Text style={[styles.floatingMenuText, { color }]}>{label}</Text></TouchableOpacity>;
}

const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: "#F7F8F6" }, content: { padding: 10, paddingBottom: 36 }, loadingBox: { flex: 1, alignItems: "center", justifyContent: "center", padding: 32 }, loadingText: { marginTop: 8, color: "#64748B", fontWeight: "800", fontSize: 12 }, errorBox: { margin: 14, backgroundColor: "#FEE2E2", borderRadius: 18, padding: 15, alignItems: "center" }, errorTitle: { color: "#991B1B", fontSize: 16, fontWeight: "900" }, errorText: { color: "#7F1D1D", marginTop: 8, textAlign: "center", fontSize: 12 }, retryButton: { marginTop: 10, backgroundColor: "#991B1B", borderRadius: 13, paddingHorizontal: 14, paddingVertical: 9 }, retryText: { color: "#fff", fontWeight: "900", fontSize: 12 },
  heroCard: { backgroundColor: "#0B1220", borderRadius: 24, padding: 12, marginBottom: 9, borderWidth: 1, borderColor: "#132237" }, heroTop: { flexDirection: "row-reverse", alignItems: "center", gap: 10, paddingTop: 8 }, heroIcon: { width: 64, height: 64, borderRadius: 21, backgroundColor: "#ECFDF5", alignItems: "center", justifyContent: "center" }, heroEmoji: { fontSize: 32 }, heroTextBox: { flex: 1, alignItems: "flex-end", paddingLeft: 28 }, heroType: { color: "#5EEAD4", fontWeight: "900", marginBottom: 3, textAlign: "right", fontSize: 12 }, heroTitle: { color: "#fff", fontSize: 19, fontWeight: "900", textAlign: "right", lineHeight: 28 }, heroLocationLine: { flexDirection: "row-reverse", alignItems: "center", gap: 4, marginTop: 4 }, heroSubtitle: { color: "#CBD5E1", fontWeight: "800", textAlign: "right", fontSize: 12 }, ownerText: { color: "#5EEAD4", fontWeight: "900", marginTop: 6, textAlign: "right", fontSize: 12 },
  tabsWrap: { flexDirection: "row-reverse", backgroundColor: "#E7E5E0", borderRadius: 19, padding: 5, marginBottom: 10, gap: 4 }, tabButton: { flex: 1, minHeight: 47, borderRadius: 16, alignItems: "center", justifyContent: "center", gap: 3 }, tabButtonActive: { backgroundColor: "#fff", shadowColor: "#0F172A", shadowOpacity: 0.07, shadowRadius: 10, shadowOffset: { width: 0, height: 5 }, elevation: 2 }, tabText: { color: "#64748B", fontWeight: "900", fontSize: 12 }, tabTextActive: { color: "#111827" },
  sectionCard: { backgroundColor: "#fff", borderRadius: 18, padding: 11, marginBottom: 9, borderWidth: 1, borderColor: "#E8EEF0", shadowColor: "#0F172A", shadowOpacity: 0.03, shadowRadius: 10, shadowOffset: { width: 0, height: 5 }, elevation: 1 }, sectionHeader: { alignItems: "flex-end", marginBottom: 10 }, sectionHeaderRow: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", marginBottom: 10, gap: 10 }, sectionHeaderText: { flex: 1, alignItems: "flex-end" }, sectionTitle: { color: "#111827", fontSize: 17, fontWeight: "900", textAlign: "right" }, sectionSubtitle: { color: "#64748B", fontWeight: "800", fontSize: 11, marginTop: 3, textAlign: "right" },
  statsGrid: { flexDirection: "row-reverse", flexWrap: "wrap", gap: 8 }, statTile: { width: "48.7%", backgroundColor: "#F8FAFC", borderRadius: 16, padding: 10, borderWidth: 1, borderColor: "#E7ECEF", minHeight: 96, alignItems: "center", justifyContent: "center" }, statTileDanger: { backgroundColor: "#FFF7ED", borderColor: "#FED7AA" }, statIconBox: { width: 42, height: 42, borderRadius: 18, backgroundColor: "#ECFDF5", alignItems: "center", justifyContent: "center", marginBottom: 7 }, statIconDanger: { backgroundColor: "#FEE2E2" }, statValue: { color: "#111827", fontWeight: "900", fontSize: 18 }, statValueDanger: { color: "#DC2626" }, statLabel: { color: "#64748B", fontWeight: "900", fontSize: 11, textAlign: "center", marginTop: 4 }, statLabelDanger: { color: "#991B1B" },
  infoRow: { borderBottomWidth: 1, borderBottomColor: "#EEF2F4", paddingVertical: 10, alignItems: "flex-end" }, infoLabel: { color: "#64748B", fontWeight: "900", fontSize: 12, marginTop: 3 }, infoValue: { color: "#111827", fontWeight: "900", fontSize: 14, textAlign: "right" }, smallAddButton: { width: 42, height: 42, borderRadius: 17, backgroundColor: "#0F9B6F", alignItems: "center", justifyContent: "center" }, emptyText: { color: "#64748B", fontWeight: "900", textAlign: "center", paddingVertical: 14, lineHeight: 24 },
  unitCard: { flexDirection: "row-reverse", gap: 10, padding: 10, borderRadius: 16, backgroundColor: "#F8FAFC", borderWidth: 1, borderColor: "#E7ECEF", marginBottom: 8, alignItems: "center" }, unitCardDanger: { backgroundColor: "#FFF7ED", borderColor: "#FED7AA" }, unitIconBox: { width: 46, height: 46, borderRadius: 17, backgroundColor: "#ECFDF5", alignItems: "center", justifyContent: "center" }, unitIconBoxDanger: { backgroundColor: "#FEE2E2" }, unitInfoBox: { flex: 1, alignItems: "flex-end" }, unitTitle: { color: "#111827", fontWeight: "900", fontSize: 16, textAlign: "right" }, unitTitleDanger: { color: "#991B1B" }, unitMeta: { color: "#64748B", fontWeight: "800", fontSize: 11, marginTop: 3 }, unitTenantText: { color: "#0F766E", fontWeight: "900", fontSize: 11, marginTop: 4 }, unitPhoneText: { color: "#64748B", fontWeight: "800", fontSize: 10, marginTop: 2 }, unitOverdueText: { color: "#DC2626", fontWeight: "900", fontSize: 11, marginTop: 4 }, unitContractOk: { color: "#0F766E", fontWeight: "900", fontSize: 11, marginTop: 4 }, unitContractEmpty: { color: "#64748B", fontWeight: "900", fontSize: 11, marginTop: 4 }, unitSideBox: { alignItems: "center", gap: 4 }, unitStatus: { color: "#0F766E", backgroundColor: "#ECFDF5", borderRadius: 999, paddingHorizontal: 9, paddingVertical: 4, fontSize: 10, fontWeight: "900" }, unitStatusDanger: { color: "#991B1B", backgroundColor: "#FEE2E2" }, unitRent: { color: "#111827", fontWeight: "900", fontSize: 11 }, unitRentDanger: { color: "#DC2626" },
  contractCard: { flexDirection: "row-reverse", gap: 10, padding: 10, borderRadius: 16, backgroundColor: "#F8FAFC", borderWidth: 1, borderColor: "#E7ECEF", marginBottom: 8, alignItems: "center" }, contractIcon: { width: 46, height: 46, borderRadius: 17, backgroundColor: "#ECFDF5", alignItems: "center", justifyContent: "center" }, contractInfo: { flex: 1, alignItems: "flex-end" }, contractTitle: { color: "#111827", fontWeight: "900", fontSize: 15, textAlign: "right" }, contractMeta: { color: "#64748B", fontWeight: "800", fontSize: 11, marginTop: 3, textAlign: "right" }, contractPhone: { color: "#0F766E", fontWeight: "900", fontSize: 11, marginTop: 3, textAlign: "right" }, contractSide: { alignItems: "center", gap: 4 }, contractStatus: { color: "#0F766E", backgroundColor: "#ECFDF5", borderRadius: 999, paddingHorizontal: 9, paddingVertical: 4, fontSize: 10, fontWeight: "900" }, contractAmount: { color: "#111827", fontWeight: "900", fontSize: 11 }, contractEmptyBox: { alignItems: "center" }, contractAddButton: { backgroundColor: "#0F9B6F", borderRadius: 15, paddingHorizontal: 16, paddingVertical: 11, flexDirection: "row-reverse", gap: 6, alignItems: "center" }, contractAddText: { color: "#fff", fontWeight: "900" },
  floatingButton: { position: "absolute", top: 26, left: 24, width: 60, height: 60, borderRadius: 30, backgroundColor: "#0F766E", alignItems: "center", justifyContent: "center", zIndex: 20, shadowColor: "#000", shadowOpacity: 0.16, shadowRadius: 10, shadowOffset: { width: 0, height: 5 }, elevation: 7 }, floatingBackdrop: { ...StyleSheet.absoluteFillObject, backgroundColor: "rgba(15, 23, 42, 0.04)", zIndex: 15 }, floatingMenu: { position: "absolute", top: 90, left: 20, width: 230, backgroundColor: "#fff", borderRadius: 22, padding: 8, zIndex: 22, borderWidth: 1, borderColor: "#E5E7EB", shadowColor: "#000", shadowOpacity: 0.12, shadowRadius: 18, shadowOffset: { width: 0, height: 8 }, elevation: 8 }, floatingMenuAction: { minHeight: 48, borderRadius: 15, paddingHorizontal: 12, flexDirection: "row-reverse", alignItems: "center", justifyContent: "space-between" }, floatingMenuText: { fontWeight: "900", fontSize: 15 },
});
